"""added foreign_key tenants.id in model Payment

Revision ID: 1cb5746acb1a
Revises: 5acc337078ad
Create Date: 2026-08-17 12:39:10.556439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cb5746acb1a'
down_revision: Union[str, Sequence[str], None] = '5acc337078ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'refund_amount',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('payments', 'maintenance_charge',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('payments_tenant_id_fkey'), 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'tenants', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key(op.f('payments_tenant_id_fkey'), 'payments', 'rooms', ['tenant_id'], ['id'])
    op.alter_column('payments', 'maintenance_charge',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('payments', 'refund_amount',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
