"""change in Tenant model foreign key beds.id

Revision ID: 4cb292cf15f1
Revises: 5e7e4944891f
Create Date: 2026-08-14 11:02:46.212221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cb292cf15f1'
down_revision: Union[str, Sequence[str], None] = '5e7e4944891f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenants', 'leave_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_constraint(op.f('tenants_bed_id_fkey'), 'tenants', type_='foreignkey')
    op.create_foreign_key(None, 'tenants', 'beds', ['bed_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tenants', type_='foreignkey')
    op.create_foreign_key(op.f('tenants_bed_id_fkey'), 'tenants', 'rooms', ['bed_id'], ['id'])
    op.alter_column('tenants', 'leave_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
