"""change aadhaar to aadhar in tenant model

Revision ID: 5acc337078ad
Revises: 4cb292cf15f1
Create Date: 2026-08-14 12:58:01.809066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5acc337078ad'
down_revision: Union[str, Sequence[str], None] = '4cb292cf15f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('aadhar_number', sa.String(length=20), nullable=False))
    op.drop_constraint(op.f('tenants_aadhaar_number_key'), 'tenants', type_='unique')
    op.create_unique_constraint(None, 'tenants', ['aadhar_number'])
    op.drop_column('tenants', 'aadhaar_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('aadhaar_number', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tenants', type_='unique')
    op.create_unique_constraint(op.f('tenants_aadhaar_number_key'), 'tenants', ['aadhaar_number'], postgresql_nulls_not_distinct=False)
    op.drop_column('tenants', 'aadhar_number')
    # ### end Alembic commands ###
