"""monthly_rent and deposite removed from bed model

Revision ID: b7dc5a6157b9
Revises: 1cb5746acb1a
Create Date: 2026-08-24 15:18:08.132570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7dc5a6157b9'
down_revision: Union[str, Sequence[str], None] = '1cb5746acb1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('beds', 'monthly_rent')
    op.drop_column('beds', 'deposite')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beds', sa.Column('deposite', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('beds', sa.Column('monthly_rent', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
